# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# scan with Anchore's Syft tool, and uploads the results to the GitHub Dependency
# submission API.

# For more information on the Anchore sbom-action usage
# and parameters, see https://github.com/anchore/sbom-action. For more
# information about the Anchore SBOM tool, Syft, see
# https://github.com/anchore/syft
name: Anchore Syft SBOM scan

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            image-tag: localbuild/testimage:latest
            artifact-name: image-spdx-json
          - dockerfile: Dockerfile-microsoft
            image-tag: localbuild/testimage-microsoft:latest
            artifact-name: image-microsoft-spdx-json
    steps:
    - name: Checkout the code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Build the Docker image
      run: docker build . --file ${{ matrix.dockerfile }} --tag ${{ matrix.image-tag }}
    - name: Scan the image and upload dependency results
      uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
      with:
        image: "${{ matrix.image-tag }}"
        artifact-name: ${{ matrix.artifact-name }}
        dependency-snapshot: true
